#ifndef GUITAR_ENGINE_OVERDRIVE_H
#define GUITAR_ENGINE_OVERDRIVE_H

#include "effect.h"
#include "oversampler.h"
#include <atomic>
#include <cmath>
#include <algorithm>
#include <vector>

/**
 * Overdrive/distortion effect with 2x oversampling.
 *
 * Overdrive is THE defining guitar effect. It emulates the warm, harmonically
 * rich distortion that occurs when a tube amplifier's preamp stage is driven
 * into saturation. The nonlinear waveshaping generates new harmonics (both
 * odd and even) that give the guitar its characteristic "crunch" tone.
 *
 * Why oversampling is needed:
 *   Waveshaping is a nonlinear operation that generates harmonics at integer
 *   multiples of the input frequency. For a guitar note at 1kHz processed at
 *   44.1kHz (Nyquist = 22.05kHz), harmonics above 22.05kHz fold back (alias)
 *   into the audible band as inharmonic, metallic-sounding artifacts.
 *
 *   2x oversampling with the smooth polynomial waveshaper used here provides
 *   sufficient alias rejection. The waveshaper is a rational polynomial (not
 *   a hard clipper), so harmonic content rolls off naturally. Industry research
 *   (Chowdhury, 2020) shows 2x oversampling with smooth nonlinearities achieves
 *   quality comparable to 4-8x with hard clippers. This reduces CPU cost by 4x
 *   compared to the previous 8x approach, enabling lower buffer sizes and
 *   reducing latency on mobile devices.
 *
 * Signal flow:
 *   Input -> Drive gain -> 2x Upsample -> Waveshaper -> 2x Downsample
 *         -> Tone filter -> Output level
 *
 * Waveshaping function:
 *   Uses a combination of soft clipping curves:
 *   - Primary: x * (27 + x^2) / (27 + 9*x^2)  -- smooth, tube-like
 *   - Asymmetric component: adds even harmonics for tube character
 *   The asymmetry models real tube behavior where positive and negative
 *   half-cycles are clipped differently due to the tube's transfer curve.
 *
 * Tone filter:
 *   A simple one-pole lowpass filter after the waveshaper. Guitar overdrive
 *   typically needs tone shaping because the harmonics generated by
 *   waveshaping can sound harsh without some high-frequency rolloff.
 *   The "tone" knob sweeps from dark (~500Hz) to bright (~8kHz).
 *
 * Parameter IDs for JNI access:
 *   0 = drive (0.0 to 1.0)
 *   1 = tone (0.0 to 1.0)
 *   2 = level (0.0 to 1.0)
 */
class Overdrive : public Effect {
public:
    Overdrive() = default;

    // =========================================================================
    // Effect interface
    // =========================================================================

    /**
     * Process audio through the overdrive. Real-time safe.
     *
     * @param buffer   Mono audio samples in [-1.0, 1.0].
     * @param numFrames Number of frames in the buffer.
     */
    void process(float* buffer, int numFrames) override {
        // Snapshot parameters
        const float drive = drive_.load(std::memory_order_relaxed);
        const float tone = tone_.load(std::memory_order_relaxed);
        const float level = level_.load(std::memory_order_relaxed);

        // ---- Step 1: Apply input drive gain ----
        // Maps drive [0, 1] to gain [1, 31] (roughly 0 to +30dB).
        // This pushes the signal into the waveshaper's nonlinear region.
        // Higher drive = more harmonics = more distortion.
        const float inputGain = 1.0f + drive * 30.0f;
        for (int i = 0; i < numFrames; ++i) {
            driveBuffer_[i] = buffer[i] * inputGain;
        }

        // ---- Step 2: Upsample 2x ----
        const int oversampledLen = oversampler_.getOversampledSize(numFrames);
        float* upsampled = oversampler_.upsample(driveBuffer_.data(), numFrames);

        // ---- Step 3: Apply waveshaping at oversampled rate ----
        for (int i = 0; i < oversampledLen; ++i) {
            upsampled[i] = waveshape(upsampled[i]);
        }

        // ---- Step 4: Downsample back to original rate ----
        oversampler_.downsample(upsampled, numFrames, buffer);

        // ---- Step 5: Apply tone filter ----
        // One-pole lowpass: y[n] = (1-a)*x[n] + a*y[n-1]
        // Cutoff frequency mapped from tone parameter:
        //   tone=0 -> ~500Hz (dark, muffled)
        //   tone=1 -> ~8000Hz (bright, present)
        // Using exponential mapping for perceptually linear sweep.
        const float cutoffHz = 500.0f * std::pow(16.0f, tone);
        const float toneCoeff = computeToneCoefficient(cutoffHz);
        const float oneMinusCoeff = 1.0f - toneCoeff;

        for (int i = 0; i < numFrames; ++i) {
            toneFilterState_ = oneMinusCoeff * buffer[i] +
                               toneCoeff * toneFilterState_;
            buffer[i] = toneFilterState_;
        }

        // ---- Step 6: Apply output level and clamp ----
        // The level control provides a volume knob after distortion.
        // Clamping to [-1, 1] prevents downstream effects from receiving
        // out-of-range samples that could cause digital clipping artifacts.
        for (int i = 0; i < numFrames; ++i) {
            buffer[i] = clamp(buffer[i] * level, -1.0f, 1.0f);
        }
    }

    /**
     * Configure sample rate and pre-allocate internal buffers.
     * @param sampleRate Device sample rate in Hz.
     */
    void setSampleRate(int32_t sampleRate) override {
        sampleRate_ = sampleRate;

        // Pre-allocate the oversampler for the maximum expected buffer size.
        // Android audio typically uses 64-480 frame buffers; 2048 gives
        // generous headroom. This is the only allocation point.
        const int maxFrames = 2048;
        oversampler_.prepare(maxFrames);

        // Pre-allocate drive buffer for input gain stage
        driveBuffer_.resize(maxFrames, 0.0f);
    }

    /**
     * Reset internal filter states. Clears the oversampler's FIR
     * history and the tone filter state to prevent artifacts when
     * the effect is re-enabled or the stream restarts.
     */
    void reset() override {
        oversampler_.reset();
        toneFilterState_ = 0.0f;
    }

    // =========================================================================
    // Parameter access (called from UI thread via JNI)
    // =========================================================================

    /**
     * Set a parameter by ID. Thread-safe.
     * @param paramId  0=drive, 1=tone, 2=level
     * @param value    Parameter value in [0.0, 1.0].
     */
    void setParameter(int paramId, float value) override {
        switch (paramId) {
            case 0:
                drive_.store(clamp(value, 0.0f, 1.0f),
                             std::memory_order_relaxed);
                break;
            case 1:
                tone_.store(clamp(value, 0.0f, 1.0f),
                            std::memory_order_relaxed);
                break;
            case 2:
                level_.store(clamp(value, 0.0f, 1.0f),
                             std::memory_order_relaxed);
                break;
            default:
                break;
        }
    }

    /**
     * Get a parameter by ID. Thread-safe.
     * @param paramId  0=drive, 1=tone, 2=level
     * @return Current parameter value.
     */
    float getParameter(int paramId) const override {
        switch (paramId) {
            case 0: return drive_.load(std::memory_order_relaxed);
            case 1: return tone_.load(std::memory_order_relaxed);
            case 2: return level_.load(std::memory_order_relaxed);
            default: return 0.0f;
        }
    }

private:
    // =========================================================================
    // Waveshaping
    // =========================================================================

    /**
     * Apply tube-like waveshaping to a single sample.
     *
     * Combines two nonlinear functions:
     * 1. Symmetric soft clipper: x*(27+x^2)/(27+9*x^2)
     *    - Approaches +/-1 asymptotically (never hard-clips)
     *    - Generates odd harmonics (3rd, 5th, 7th...)
     *    - Sounds smooth and warm
     *
     * 2. Asymmetric component: adds a small even-harmonic bias
     *    - Real tubes clip positive and negative half-cycles differently
     *    - Even harmonics (2nd, 4th) add warmth and "fatness"
     *    - We add a subtle quadratic term scaled by the input
     *
     * The mix is carefully tuned to sound like a moderately driven
     * tube preamp stage rather than a transistor fuzz.
     *
     * @param x Input sample (can be > 1.0 after drive gain).
     * @return Waveshaped sample, approximately in [-1.0, 1.0].
     */
    static float waveshape(float x) {
        // Primary symmetric soft clipper
        // This is a rational function that saturates smoothly.
        // At small x, output ~= x (linear, clean).
        // At large x, output -> +/- 1 (saturated, distorted).
        const float x2 = x * x;
        float symmetric = x * (27.0f + x2) / (27.0f + 9.0f * x2);

        // Asymmetric component for even harmonics (tube character).
        // The quadratic term x^2 generates 2nd harmonics.
        // We scale by 0.1 to keep it subtle -- too much asymmetry
        // sounds buzzy rather than warm.
        // The divisor (1 + |x|) prevents the asymmetric term from
        // growing unbounded at high input levels.
        float asymmetric = 0.1f * x2 / (1.0f + std::abs(x));

        // Combine: the asymmetric term shifts the zero crossing slightly,
        // creating the characteristic even-harmonic content of tubes.
        return symmetric + asymmetric;
    }

    /**
     * Compute one-pole lowpass filter coefficient from cutoff frequency.
     *
     * The coefficient 'a' for a one-pole filter y[n] = (1-a)*x[n] + a*y[n-1]:
     *   a = exp(-2*pi*fc/fs)
     *
     * where fc is cutoff frequency and fs is sample rate.
     *
     * @param cutoffHz Desired cutoff frequency in Hz.
     * @return Filter coefficient (higher = more filtering/darker).
     */
    float computeToneCoefficient(float cutoffHz) const {
        if (sampleRate_ <= 0) return 0.0f;
        // Clamp cutoff to valid range (above 0, below Nyquist)
        cutoffHz = clamp(cutoffHz, 20.0f,
                         static_cast<float>(sampleRate_) * 0.49f);
        return std::exp(-2.0f * static_cast<float>(M_PI) * cutoffHz /
                        static_cast<float>(sampleRate_));
    }

    /**
     * Clamp a value to a range.
     */
    static float clamp(float value, float minVal, float maxVal) {
        return std::max(minVal, std::min(maxVal, value));
    }

    // =========================================================================
    // Parameters (written from UI thread, read from audio thread)
    // =========================================================================

    std::atomic<float> drive_{0.5f};   // [0, 1] drive amount
    std::atomic<float> tone_{0.5f};    // [0, 1] tone (dark to bright)
    std::atomic<float> level_{0.7f};   // [0, 1] output level

    // =========================================================================
    // Audio thread state
    // =========================================================================

    int32_t sampleRate_ = 44100;
    Oversampler<2> oversampler_;
    float toneFilterState_ = 0.0f;  // One-pole LPF state

    // Pre-allocated buffer for the drive-gain stage (before upsampling).
    // Avoids writing the gained signal back to the input buffer, which
    // would corrupt the dry signal if wet/dry mixing is used.
    std::vector<float> driveBuffer_;
};

#endif // GUITAR_ENGINE_OVERDRIVE_H
