#ifndef GUITAR_ENGINE_OVERSAMPLER_H
#define GUITAR_ENGINE_OVERSAMPLER_H

#include <cmath>
#include <cstdint>
#include <cstring>
#include <vector>

/**
 * Reusable oversampler for anti-aliased nonlinear processing.
 *
 * Oversampling moves the Nyquist frequency higher before applying waveshaping,
 * so that harmonics generated by nonlinear functions fall above the original
 * Nyquist and are removed by the anti-aliasing filter during downsampling.
 * Without oversampling, these harmonics alias back into the audible band as
 * inharmonic distortion artifacts.
 *
 * Process flow:
 *   1. Upsample: zero-stuff by Factor, then apply FIR lowpass
 *   2. Process:  apply nonlinear function at the oversampled rate
 *   3. Downsample: apply FIR lowpass, then decimate by Factor
 *
 * The FIR filter uses a Kaiser-windowed sinc design. Kaiser window provides
 * a good tradeoff between main lobe width and sidelobe attenuation, and
 * the beta parameter allows tuning the stopband rejection.
 *
 * Template parameter Factor controls the oversampling ratio (default 8x).
 * Higher factors give better alias rejection at the cost of more CPU.
 *
 * All buffers are pre-allocated in prepare() to ensure real-time safety
 * in the process path.
 */
template<int Factor = 8>
class Oversampler {
public:
    Oversampler() = default;

    /**
     * Pre-allocate all internal buffers for the given maximum block size.
     * Must be called before any processing, typically in setSampleRate().
     * This is the ONLY method that allocates memory.
     *
     * @param maxFrames Maximum number of input frames per process() call.
     */
    void prepare(int maxFrames) {
        maxFrames_ = maxFrames;
        const int oversampledSize = maxFrames * Factor;

        // Oversampled buffer holds the upsampled signal
        oversampledBuffer_.resize(oversampledSize, 0.0f);

        // FIR filter delay line for upsampling and downsampling
        // Size must accommodate the full filter kernel
        upsampleHistory_.resize(kFilterOrder, 0.0f);
        downsampleHistory_.resize(kFilterOrder, 0.0f);

        generateFilterCoefficients();
    }

    /**
     * Reset all internal filter state (delay lines).
     * Call when the audio stream restarts or the effect is bypassed/re-enabled
     * to prevent stale samples from the previous signal from leaking through.
     */
    void reset() {
        std::fill(upsampleHistory_.begin(), upsampleHistory_.end(), 0.0f);
        std::fill(downsampleHistory_.begin(), downsampleHistory_.end(), 0.0f);
        upsampleHistoryIdx_ = 0;
        downsampleHistoryIdx_ = 0;
    }

    /**
     * Get the oversampled buffer size for a given input frame count.
     * @param numFrames Number of input frames.
     * @return Number of oversampled frames (numFrames * Factor).
     */
    int getOversampledSize(int numFrames) const {
        return numFrames * Factor;
    }

    /**
     * Upsample the input buffer by Factor.
     * Zero-stuffs then applies the anti-imaging FIR lowpass filter.
     * Result is written to the internal oversampled buffer.
     *
     * @param input  Input samples (numFrames floats).
     * @param numFrames Number of input frames.
     * @return Pointer to internal oversampled buffer (numFrames * Factor floats).
     */
    float* upsample(const float* input, int numFrames) {
        const int oversampledLen = numFrames * Factor;

        // Step 1: Zero-stuff -- insert (Factor-1) zeros between each input sample.
        // The gain factor compensates for the energy loss from zero-stuffing.
        for (int i = 0; i < numFrames; ++i) {
            oversampledBuffer_[i * Factor] = input[i] * static_cast<float>(Factor);
            for (int j = 1; j < Factor; ++j) {
                oversampledBuffer_[i * Factor + j] = 0.0f;
            }
        }

        // Step 2: Apply anti-imaging FIR lowpass filter
        applyFIR(oversampledBuffer_.data(), oversampledLen,
                 upsampleHistory_.data(), upsampleHistoryIdx_);

        return oversampledBuffer_.data();
    }

    /**
     * Downsample the oversampled buffer back to the original rate.
     * Applies anti-aliasing FIR lowpass filter, then decimates by Factor.
     *
     * @param oversampledInput Oversampled samples (numFrames * Factor floats).
     *                          Can be the internal buffer from upsample().
     * @param numFrames Original (non-oversampled) frame count.
     * @param output Output buffer for decimated samples (numFrames floats).
     */
    void downsample(const float* oversampledInput, int numFrames, float* output) {
        const int oversampledLen = numFrames * Factor;

        // Copy to internal buffer if the source is not already our buffer
        // (it typically IS our buffer, but we handle both cases for safety)
        if (oversampledInput != oversampledBuffer_.data()) {
            std::memcpy(oversampledBuffer_.data(), oversampledInput,
                        oversampledLen * sizeof(float));
        }

        // Step 1: Apply anti-aliasing FIR lowpass filter
        applyFIR(oversampledBuffer_.data(), oversampledLen,
                 downsampleHistory_.data(), downsampleHistoryIdx_);

        // Step 2: Decimate -- pick every Factor-th sample
        for (int i = 0; i < numFrames; ++i) {
            output[i] = oversampledBuffer_[i * Factor];
        }
    }

    /**
     * Get direct access to the internal oversampled buffer.
     * Use this to apply processing at the oversampled rate between
     * upsample() and downsample() calls.
     *
     * @return Pointer to the internal oversampled buffer.
     */
    float* getOversampledBuffer() {
        return oversampledBuffer_.data();
    }

private:
    /**
     * FIR filter order. Higher order = sharper cutoff and better stopband
     * rejection, but more CPU cost per sample.
     *
     * 63 taps (order 62) provides approximately 60-70dB of stopband
     * rejection with an 8x oversampling factor, which is sufficient
     * for guitar overdrive where some residual aliasing is musically
     * acceptable. Professional mastering tools might use 127+ taps.
     */
    static constexpr int kFilterOrder = 63;

    /**
     * Kaiser window beta parameter. Controls the tradeoff between
     * main lobe width and sidelobe attenuation.
     *   beta = 4.0 gives ~40dB attenuation (good for audio)
     *   beta = 6.0 gives ~60dB attenuation
     *   beta = 8.0 gives ~80dB attenuation
     *
     * We use 6.0 as a good balance for guitar effects processing.
     */
    static constexpr float kKaiserBeta = 6.0f;

    /**
     * Generate the FIR lowpass filter coefficients using a
     * Kaiser-windowed sinc function.
     *
     * The cutoff frequency is set to 1/(2*Factor) of the oversampled
     * Nyquist, which corresponds to the original Nyquist frequency.
     * This removes all frequency content above the original Nyquist
     * that would alias when decimating.
     */
    void generateFilterCoefficients() {
        coefficients_.resize(kFilterOrder);

        const float cutoff = 1.0f / static_cast<float>(Factor);
        const int halfOrder = kFilterOrder / 2;

        // Generate windowed sinc coefficients
        float sum = 0.0f;
        for (int i = 0; i < kFilterOrder; ++i) {
            const float n = static_cast<float>(i - halfOrder);

            // Sinc function: sin(pi * cutoff * n) / (pi * n)
            float sinc;
            if (std::abs(n) < 1e-6f) {
                sinc = cutoff; // L'Hopital limit at n=0
            } else {
                const float x = static_cast<float>(M_PI) * n * cutoff;
                sinc = std::sin(x) / (static_cast<float>(M_PI) * n);
            }

            // Kaiser window value at this position
            float window = kaiserWindow(i, kFilterOrder, kKaiserBeta);

            coefficients_[i] = sinc * window;
            sum += coefficients_[i];
        }

        // Normalize so the filter has unity gain at DC.
        // Without normalization, the passband gain would deviate from 1.0
        // causing volume changes when the oversampler is engaged.
        if (sum > 0.0f) {
            const float invSum = 1.0f / sum;
            for (int i = 0; i < kFilterOrder; ++i) {
                coefficients_[i] *= invSum;
            }
        }
    }

    /**
     * Compute the Kaiser window function at position n.
     *
     * W(n) = I0(beta * sqrt(1 - ((2n/(N-1)) - 1)^2)) / I0(beta)
     *
     * where I0 is the zero-order modified Bessel function of the first kind.
     *
     * @param n     Sample index in [0, N-1].
     * @param N     Window length.
     * @param beta  Shape parameter controlling sidelobe attenuation.
     * @return Window value at position n.
     */
    static float kaiserWindow(int n, int N, float beta) {
        const float halfN = static_cast<float>(N - 1) / 2.0f;
        const float norm = (static_cast<float>(n) - halfN) / halfN;
        const float arg = beta * std::sqrt(std::max(0.0f, 1.0f - norm * norm));
        return besselI0(arg) / besselI0(beta);
    }

    /**
     * Approximate the zero-order modified Bessel function of the first kind.
     * Uses the standard series expansion which converges rapidly for
     * the range of arguments we encounter (beta typically 4-10).
     *
     * I0(x) = sum_{k=0}^{inf} [(x/2)^k / k!]^2
     *
     * We use 20 terms which gives machine-precision accuracy for beta <= 12.
     */
    static float besselI0(float x) {
        float sum = 1.0f;
        float term = 1.0f;
        const float halfX = x / 2.0f;

        for (int k = 1; k <= 20; ++k) {
            term *= (halfX / static_cast<float>(k));
            sum += term * term;
        }
        return sum;
    }

    /**
     * Apply FIR filter in-place using a circular buffer (history).
     *
     * Uses a circular buffer instead of shifting the delay line on every
     * sample. The write position (historyIdx) advances by 1 each sample,
     * wrapping around at kFilterOrder. Convolution reads backwards from
     * historyIdx with modular wrap-around.
     *
     * Produces identical output to a shift-based implementation:
     *   coefficients_[0] multiplies the newest sample,
     *   coefficients_[kFilterOrder-1] multiplies the oldest sample.
     *
     * Complexity per sample: O(kFilterOrder) multiply-accumulates (unchanged),
     * but the O(kFilterOrder) history shift is eliminated, replaced by a
     * single write + index increment.
     *
     * @param buffer     Audio samples to filter in-place.
     * @param numSamples Number of samples in the buffer.
     * @param history    Circular delay line of size kFilterOrder, preserved between calls.
     * @param historyIdx Write index into the circular buffer, preserved between calls.
     */
    void applyFIR(float* buffer, int numSamples, float* history, int& historyIdx) {
        for (int i = 0; i < numSamples; ++i) {
            const float inputSample = buffer[i];

            // Write the new sample at the current circular buffer position.
            // This overwrites the oldest sample in the history.
            history[historyIdx] = inputSample;

            // Convolution: accumulate coefficients * history samples.
            // coefficients_[0] pairs with the newest sample (at historyIdx),
            // coefficients_[1] pairs with the next-oldest (historyIdx - 1), etc.
            // Reading backwards with modular wrap-around avoids shifting.
            float output = 0.0f;
            int readIdx = historyIdx;
            for (int j = 0; j < kFilterOrder; ++j) {
                output += history[readIdx] * coefficients_[j];
                // Decrement with wrap-around (branchless for kFilterOrder)
                if (--readIdx < 0) readIdx = kFilterOrder - 1;
            }

            buffer[i] = output;

            // Advance write position with wrap-around
            if (++historyIdx >= kFilterOrder) historyIdx = 0;
        }
    }

    int maxFrames_ = 0;
    std::vector<float> oversampledBuffer_;
    std::vector<float> coefficients_;
    std::vector<float> upsampleHistory_;
    std::vector<float> downsampleHistory_;

    /** Circular buffer write index for the upsample FIR history. */
    int upsampleHistoryIdx_ = 0;

    /** Circular buffer write index for the downsample FIR history. */
    int downsampleHistoryIdx_ = 0;
};

#endif // GUITAR_ENGINE_OVERSAMPLER_H
