#ifndef GUITAR_ENGINE_SUBTRACTIVE_VOICE_H
#define GUITAR_ENGINE_SUBTRACTIVE_VOICE_H

#include <atomic>
#include <cmath>
#include <cstdint>

#include "../drum_voice.h"
#include "../../effects/fast_math.h"

/**
 * Analog subtractive drum voice.
 *
 * Signal flow:
 *   [Tone Osc (sine)] + [Noise] -> [Mixer] -> [SVF LP] -> [Amp Env] -> out
 *
 * The tone oscillator uses a 1024-point sine wavetable with linear
 * interpolation and a short pitch envelope for the initial transient "snap"
 * (frequency sweeps down from 2x toneFreq to toneFreq over ~5ms).
 *
 * White noise is generated by a xorshift32 PRNG (period 2^32-1, fast,
 * no state dependencies).
 *
 * Two independent amplitude envelopes (toneEnv, noiseEnv) allow separate
 * decay control over the tonal body and noise transient. The noiseMix
 * parameter crossfades between the two enveloped signals.
 *
 * The SVF filter (TPT form, lowpass) has its own envelope that sweeps
 * the cutoff from an elevated frequency down to the base filterFreq,
 * controlled by filterEnvDepth (in octaves) and filterDecay.
 *
 * Intended for: snares, claps, rimshots, toms, percussion.
 *
 * Parameter IDs:
 *   0: toneFreq      (80-800 Hz)     Base frequency of tone oscillator
 *   1: toneDecay      (10-500 ms)     Tone amplitude envelope decay time
 *   2: noiseDecay     (10-500 ms)     Noise amplitude envelope decay time
 *   3: noiseMix       (0-1)           Blend: 0=pure tone, 1=pure noise
 *   4: filterFreq     (200-16000 Hz)  SVF filter base cutoff frequency
 *   5: filterRes      (0-1)           SVF filter resonance
 *   6: filterDecay    (5-500 ms)      Filter envelope decay time
 *   7: filterEnvDepth (0-8 octaves)   Filter envelope sweep range
 *   8: drive          (0-5)           Pre-filter saturation amount
 *
 * Thread safety:
 *   All parameters stored as std::atomic<float> for lock-free UI updates.
 *   Envelope coefficients are re-derived per block from atomic param reads.
 */

namespace drums {

class SubtractiveVoice : public DrumVoice {
public:
    SubtractiveVoice() {
        initSineTable();
        // Set sensible defaults
        params_[0].store(200.0f, std::memory_order_relaxed);  // toneFreq
        params_[1].store(100.0f, std::memory_order_relaxed);  // toneDecay ms
        params_[2].store(60.0f,  std::memory_order_relaxed);  // noiseDecay ms
        params_[3].store(0.5f,   std::memory_order_relaxed);  // noiseMix
        params_[4].store(4000.0f,std::memory_order_relaxed);  // filterFreq
        params_[5].store(0.2f,   std::memory_order_relaxed);  // filterRes
        params_[6].store(50.0f,  std::memory_order_relaxed);  // filterDecay ms
        params_[7].store(2.0f,   std::memory_order_relaxed);  // filterEnvDepth
        params_[8].store(0.0f,   std::memory_order_relaxed);  // drive
    }

    // ----------------------------------------------------------------
    // DrumVoice interface
    // ----------------------------------------------------------------

    /**
     * Trigger the voice with a given velocity.
     *
     * Resets oscillator phase, envelope values, pitch envelope, and
     * filter state. The velocity scales the overall output amplitude.
     *
     * @param velocity Note velocity in [0.0, 1.0].
     */
    void trigger(float velocity) override {
        velocity_ = velocity;
        tonePhase_ = 0.0f;
        toneEnv_ = 1.0f;
        noiseEnv_ = 1.0f;
        filterEnv_ = 1.0f;
        pitchEnv_ = 1.0f;
        active_ = true;
        fadeCounter_ = 0;
        fadeGain_ = 1.0f;

        // Reset SVF filter state to avoid transient from previous note
        svfIc1eq_ = 0.0f;
        svfIc2eq_ = 0.0f;

        // Re-derive envelope coefficients from current params
        updateCoefficients();
    }

    /**
     * Generate one output sample.
     *
     * Per-sample signal flow:
     *   1. Generate tone sample from sine wavetable with pitch envelope
     *   2. Generate noise sample from xorshift32 PRNG
     *   3. Apply individual amplitude envelopes and mix by noiseMix
     *   4. Apply drive saturation (fast_tanh)
     *   5. Apply SVF lowpass with filter envelope on cutoff
     *   6. Scale by velocity
     *   7. Apply choke fade if active
     *   8. Deactivate when both envelopes fall below silence threshold
     *
     * @return Audio sample in approximately [-1.0, 1.0].
     */
    float process() override {
        if (!active_) return 0.0f;

        // --- Read params (relaxed atomics, block-rate would be ideal
        //     but per-sample read is acceptable for 9 params) ---
        const float toneFreq     = params_[0].load(std::memory_order_relaxed);
        const float noiseMix     = params_[3].load(std::memory_order_relaxed);
        const float filterFreq   = params_[4].load(std::memory_order_relaxed);
        const float filterRes    = params_[5].load(std::memory_order_relaxed);
        const float filterDepth  = params_[7].load(std::memory_order_relaxed);
        const float driveAmt     = params_[8].load(std::memory_order_relaxed);

        // --- 1. Tone oscillator with pitch envelope ---
        // Pitch envelope adds a brief upward sweep for transient "snap".
        // Sweeps from 2x toneFreq down to toneFreq as pitchEnv decays 1->0.
        float currentFreq = toneFreq * (1.0f + pitchEnv_);
        float phaseInc = currentFreq / sampleRateF_;
        tonePhase_ += phaseInc;
        if (tonePhase_ >= 1.0f) tonePhase_ -= 1.0f;

        float toneSample = sineLookup(tonePhase_);

        // Decay pitch envelope (~5ms exponential decay, fixed)
        pitchEnv_ *= pitchEnvCoeff_;

        // --- 2. White noise via xorshift32 ---
        float noiseSample = xorshift32Noise();

        // --- 3. Apply individual amp envelopes and mix ---
        float toneMixed  = toneSample * toneEnv_ * (1.0f - noiseMix);
        float noiseMixed = noiseSample * noiseEnv_ * noiseMix;
        float mixed = toneMixed + noiseMixed;

        // Decay amplitude envelopes
        toneEnv_ *= toneEnvCoeff_;
        noiseEnv_ *= noiseEnvCoeff_;

        // --- 4. Drive saturation (skip if negligible for efficiency) ---
        if (driveAmt > 0.01f) {
            mixed = fast_math::fast_tanh(mixed * (1.0f + driveAmt * 4.0f));
        }

        // --- 5. SVF lowpass filter with filter envelope ---
        // Filter envelope sweeps cutoff: filterFreq * 2^(depth * env) -> filterFreq
        float envCutoff = filterFreq * fast_math::exp2_approx(filterDepth * filterEnv_);

        // Clamp cutoff to safe range [20, Nyquist*0.49]
        float nyquistLimit = sampleRateF_ * 0.49f;
        if (envCutoff < 20.0f) envCutoff = 20.0f;
        if (envCutoff > nyquistLimit) envCutoff = nyquistLimit;

        // Update SVF coefficients for this sample's cutoff
        updateSVFCoefficients(envCutoff, filterRes);

        // Process through SVF LP
        mixed = processSVF(mixed);

        // Decay filter envelope
        filterEnv_ *= filterEnvCoeff_;

        // --- 6. Velocity scaling ---
        float output = mixed * velocity_;

        // --- 7. Choke fade ---
        output = applyFade(output);

        // --- 8. Check silence threshold ---
        // Deactivate when both amp envelopes are below threshold
        // and filter envelope is also decayed (to avoid cutting off filter tail)
        if (toneEnv_ < kSilenceThreshold && noiseEnv_ < kSilenceThreshold) {
            active_ = false;
            return 0.0f;
        }

        return output;
    }

    /**
     * Set a synthesis parameter by ID. Thread-safe (atomic store).
     *
     * @param paramId Parameter index 0-8 (see class header for mapping).
     * @param value   Parameter value (clamped to valid range internally).
     */
    void setParam(int paramId, float value) override {
        if (paramId < 0 || paramId >= kNumParams) return;

        // Clamp to valid ranges
        switch (paramId) {
            case 0: value = clamp(value, 80.0f, 800.0f);    break; // toneFreq
            case 1: value = clamp(value, 10.0f, 500.0f);    break; // toneDecay
            case 2: value = clamp(value, 10.0f, 500.0f);    break; // noiseDecay
            case 3: value = clamp(value, 0.0f, 1.0f);       break; // noiseMix
            case 4: value = clamp(value, 200.0f, 16000.0f); break; // filterFreq
            case 5: value = clamp(value, 0.0f, 1.0f);       break; // filterRes
            case 6: value = clamp(value, 5.0f, 500.0f);     break; // filterDecay
            case 7: value = clamp(value, 0.0f, 8.0f);       break; // filterEnvDepth
            case 8: value = clamp(value, 0.0f, 5.0f);       break; // drive
            default: break;
        }

        params_[paramId].store(value, std::memory_order_relaxed);
    }

    /**
     * Get a synthesis parameter by ID. Thread-safe (atomic load).
     *
     * @param paramId Parameter index 0-8.
     * @return Current parameter value, or 0.0f for unknown IDs.
     */
    float getParam(int paramId) const override {
        if (paramId < 0 || paramId >= kNumParams) return 0.0f;
        return params_[paramId].load(std::memory_order_relaxed);
    }

    /**
     * Set the audio sample rate. Recalculates all rate-dependent
     * coefficients (envelope decay rates, pitch envelope, SVF state).
     *
     * @param sr Device native sample rate in Hz.
     */
    void setSampleRate(int32_t sr) override {
        sampleRate_ = sr;
        sampleRateF_ = static_cast<float>(sr);

        // Pre-compute pitch envelope coefficient (~5ms decay, fixed)
        // coeff = exp(-1 / (decaySeconds * sampleRate))
        float pitchDecaySec = 0.005f;
        pitchEnvCoeff_ = std::exp(-1.0f / (pitchDecaySec * sampleRateF_));

        // Reset filter state
        svfIc1eq_ = 0.0f;
        svfIc2eq_ = 0.0f;

        // Recalculate envelope coefficients
        updateCoefficients();
    }

    /**
     * Reset all internal state: oscillator phase, envelopes, filter history.
     * Called when the audio stream restarts.
     */
    void reset() override {
        active_ = false;
        tonePhase_ = 0.0f;
        toneEnv_ = 0.0f;
        noiseEnv_ = 0.0f;
        filterEnv_ = 0.0f;
        pitchEnv_ = 0.0f;
        velocity_ = 0.0f;
        svfIc1eq_ = 0.0f;
        svfIc2eq_ = 0.0f;
        fadeCounter_ = 0;
        fadeGain_ = 1.0f;
    }

private:
    // ----------------------------------------------------------------
    // Constants
    // ----------------------------------------------------------------

    static constexpr int   kTableSize = 1024;          ///< Sine wavetable size
    static constexpr int   kNumParams = 9;             ///< Number of voice params
    static constexpr float kSilenceThreshold = 0.0001f; ///< -80 dB envelope cutoff

    // ----------------------------------------------------------------
    // Sine wavetable (shared across all SubtractiveVoice instances)
    // ----------------------------------------------------------------

    /**
     * Static 1024-point sine wavetable.
     * Initialized once on first construction via initSineTable().
     * Thread-safe: worst case two voices call init concurrently and both
     * write identical values. The tableReady flag prevents repeated init.
     */
    static inline float sineTable_[kTableSize];
    static inline bool tableReady_ = false;

    static void initSineTable() {
        if (tableReady_) return;
        for (int i = 0; i < kTableSize; ++i) {
            sineTable_[i] = std::sin(2.0f * 3.14159265f * static_cast<float>(i)
                                     / static_cast<float>(kTableSize));
        }
        tableReady_ = true;
    }

    /**
     * Wavetable lookup with linear interpolation.
     * Phase is normalized [0, 1) representing one full cycle.
     *
     * @param phase Normalized phase in [0, 1).
     * @return Sine value at the given phase.
     */
    static float sineLookup(float phase) {
        float idx = phase * static_cast<float>(kTableSize);
        int i0 = static_cast<int>(idx) & (kTableSize - 1);
        int i1 = (i0 + 1) & (kTableSize - 1);
        float frac = idx - std::floor(idx);
        return sineTable_[i0] + frac * (sineTable_[i1] - sineTable_[i0]);
    }

    // ----------------------------------------------------------------
    // Noise generator (xorshift32 PRNG)
    // ----------------------------------------------------------------

    /**
     * Generate one white noise sample via xorshift32.
     * Output normalized to [-1.0, 1.0].
     *
     * @return White noise sample.
     */
    float xorshift32Noise() {
        rngState_ ^= rngState_ << 13;
        rngState_ ^= rngState_ >> 17;
        rngState_ ^= rngState_ << 5;
        return static_cast<float>(static_cast<int32_t>(rngState_))
               / static_cast<float>(INT32_MAX);
    }

    // ----------------------------------------------------------------
    // SVF filter (TPT form, lowpass mode)
    // ----------------------------------------------------------------

    /**
     * Update SVF coefficients for the given cutoff and resonance.
     * Uses TPT (topology-preserving transform) for stability at high cutoff.
     *
     * @param cutoff Cutoff frequency in Hz (already clamped).
     * @param res    Resonance in [0, 1].
     */
    void updateSVFCoefficients(float cutoff, float res) {
        // g = tan(pi * fc / fs) via fast approximation
        double g = fast_math::tan_approx(
            3.14159265358979 * static_cast<double>(cutoff) / static_cast<double>(sampleRate_));
        svfG_ = static_cast<float>(g);

        // Damping: k = 2*(1-res), res=0 => no resonance, res=1 => self-oscillation
        svfK_ = 2.0f * (1.0f - res);

        // Pre-compute coefficients
        svfA1_ = 1.0f / (1.0f + svfG_ * (svfG_ + svfK_));
        svfA2_ = svfG_ * svfA1_;
        svfA3_ = svfG_ * svfA2_;
    }

    /**
     * Process one sample through the SVF lowpass filter.
     *
     * @param input Input sample.
     * @return Lowpass filtered output.
     */
    float processSVF(float input) {
        float v3 = input - svfIc2eq_;
        float v1 = svfA1_ * svfIc1eq_ + svfA2_ * v3;
        float v2 = svfIc2eq_ + svfA2_ * svfIc1eq_ + svfA3_ * v3;
        svfIc1eq_ = 2.0f * v1 - svfIc1eq_;
        svfIc2eq_ = 2.0f * v2 - svfIc2eq_;

        // Denormal guard on filter state
        svfIc1eq_ = fast_math::denormal_guard(svfIc1eq_);
        svfIc2eq_ = fast_math::denormal_guard(svfIc2eq_);

        return v2; // Lowpass output
    }

    // ----------------------------------------------------------------
    // Envelope coefficient computation
    // ----------------------------------------------------------------

    /**
     * Re-derive all envelope decay coefficients from current atomic params.
     * Called on trigger() and setSampleRate() to pre-compute per-sample
     * multipliers. Formula: coeff = exp(-1 / (decaySeconds * sampleRate)).
     */
    void updateCoefficients() {
        if (sampleRate_ <= 0) return;

        float toneDecayMs  = params_[1].load(std::memory_order_relaxed);
        float noiseDecayMs = params_[2].load(std::memory_order_relaxed);
        float filterDecayMs = params_[6].load(std::memory_order_relaxed);

        // Convert ms to seconds, compute exponential decay coefficient
        toneEnvCoeff_   = std::exp(-1.0f / (toneDecayMs * 0.001f * sampleRateF_));
        noiseEnvCoeff_  = std::exp(-1.0f / (noiseDecayMs * 0.001f * sampleRateF_));
        filterEnvCoeff_ = std::exp(-1.0f / (filterDecayMs * 0.001f * sampleRateF_));
    }

    // ----------------------------------------------------------------
    // Utility
    // ----------------------------------------------------------------

    static float clamp(float v, float lo, float hi) {
        if (v < lo) return lo;
        if (v > hi) return hi;
        return v;
    }

    // ----------------------------------------------------------------
    // Parameters (UI thread writes, audio thread reads)
    // ----------------------------------------------------------------

    std::atomic<float> params_[kNumParams]{};

    // ----------------------------------------------------------------
    // Audio-thread-only state
    // ----------------------------------------------------------------

    int32_t sampleRate_ = 48000;
    float   sampleRateF_ = 48000.0f;

    // Oscillator
    float tonePhase_ = 0.0f;           ///< Tone osc phase [0, 1)

    // Amplitude envelopes
    float toneEnv_ = 0.0f;             ///< Tone amplitude envelope level
    float noiseEnv_ = 0.0f;            ///< Noise amplitude envelope level
    float toneEnvCoeff_ = 0.999f;      ///< Per-sample tone decay multiplier
    float noiseEnvCoeff_ = 0.999f;     ///< Per-sample noise decay multiplier

    // Pitch envelope (fixed ~5ms decay for transient snap)
    float pitchEnv_ = 0.0f;            ///< Pitch envelope level [0, 1]
    float pitchEnvCoeff_ = 0.999f;     ///< Per-sample pitch decay multiplier

    // Filter envelope
    float filterEnv_ = 0.0f;           ///< Filter envelope level [0, 1]
    float filterEnvCoeff_ = 0.999f;    ///< Per-sample filter env decay multiplier

    // SVF filter state (audio thread only)
    float svfG_ = 0.0f;                ///< TPT coefficient g = tan(pi*fc/fs)
    float svfK_ = 2.0f;                ///< Damping 2*(1-res)
    float svfA1_ = 0.0f;               ///< Pre-computed: 1/(1+g*(g+k))
    float svfA2_ = 0.0f;               ///< Pre-computed: g*a1
    float svfA3_ = 0.0f;               ///< Pre-computed: g*a2
    float svfIc1eq_ = 0.0f;            ///< SVF integrator state 1
    float svfIc2eq_ = 0.0f;            ///< SVF integrator state 2

    // Velocity
    float velocity_ = 0.0f;            ///< Trigger velocity [0, 1]

    // PRNG state (non-zero seed required for xorshift32)
    uint32_t rngState_ = 0xDEADBEEF;
};

} // namespace drums

#endif // GUITAR_ENGINE_SUBTRACTIVE_VOICE_H
